### ISSUE TITLE
Sold. I'm in.

### ISSUE THREAD

**Issue by acomito** [ydeshayes/googlePlaceAutocomplete#1]
in.

maybe referencing material-ui in the npm package could be good (for marketing purposes).

material-ui-googleplaces
material-ui-places

also maybe worth checking out (for roadmap purposes):

https://github.com/ubilabs/react-geosuggest
https://github.com/callemall/material-ui/issues/5235

**Comment by ydeshayes** [comment]
Hi ! 

Yes maybe a name with material-ui in it will be better, I will look at the features !  Maybe you can already make a list with what you have in mind ?

Thanks !

**Comment by ydeshayes** [comment]
@acomito
