### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by dynnt27** [ydeshayes/googlePlaceAutocomplete#12]
whats with on change and onNewRequest? Can you provide a much better getting started?

**Comment by ydeshayes** [comment]
Hello,

Did you look at https://github.com/ydeshayes/googlePlaceAutocompleteExample/blob/master/src/App.js? this is the source of the example app.

I will add onChange in the README.

**Comment by dynnt27** [comment]
Thanks I already found it by clicking on your profile.
