### ISSUE TITLE
Npm version has no lib

### ISSUE THREAD

**Issue by steelbrain** [ydeshayes/googlePlaceAutocomplete#3]
The version `1.0.3` in npm has no `lib` directory. I tried uploading a screenshot of the installed package but at the time of writing ec2 is having a downtime so github images servers are down

**Comment by ydeshayes** [comment]
Hello,

I've just update to ```1.0.4```that correct this problem. https://www.npmjs.com/package/material-ui-places.


Thanks for reporting this issue.

**Comment by steelbrain** [comment]
Thanks
