### ISSUE TITLE
Add example link

### ISSUE THREAD

**Issue by tifa2UP** [ydeshayes/googlePlaceAutocomplete#4]
Hey @ydeshayes, great work! It'd be awesome if you build an example and show it so that we can get an idea of how it is like before using it.

**Comment by ydeshayes** [comment]
Hello @tifa2UP I push a simple example page here https://ydeshayes.github.io/googlePlaceAutocomplete/ I will push the source code later.

**Comment by jwamsterdam** [comment]
Hi, source code is really needed! thnx in advance

**Comment by ydeshayes** [comment]
Hi ! you can find it here https://github.com/ydeshayes/googlePlaceAutocompleteExample :)

**Comment by jwamsterdam** [comment]
Great, that works super!
two questions: 
- I need to get te geo coordinates back, can you assist me in how to obtain (console.log) these values?
- Some addresses I click on in the dropdown, provide me an error saying: 

`Uncaught TypeError: Cannot read property 'description' of undefined
    at Object.OriginAddress._this.onClickEverywhereLocationFct [as onNewRequest] (OriginAddress.js:24)
    at t.value (material-ui-places.min.js:1)
    at AutoComplete.js:158`

**Comment by ydeshayes** [comment]
Thanks for your feedbacks ! 👍 

- I look quickly at the way you can get the coordinates back, you can use the ```place_id``` you get in the object return in the onNewRequest callback function and call the API described here => https://developers.google.com/places/web-service/details?hl=fr .

- I will investigate on this bug.

**Comment by jwamsterdam** [comment]
Hi have tried to do the fetch with the google API and places_id, this works, but I do have a CORS issue. I think it will be overkill to import another NPM just for this call. Do you think you can add this functionality one way or the other to your NPM?

**Comment by jwamsterdam** [comment]
I get this error still quite a lot (which is the same as a few posts above:

Uncaught TypeError: Cannot read property 'place_id' of undefined
    at Object.o.onClickEverywhereLocationFct [as onNewRequest] (AddressInput.js:19)
    at t.value (material-ui-places.min.js:1)
    at AutoComplete.js:158

**Comment by jwamsterdam** [comment]
I did some debugging and found a way to reproduce!
If you enter an address in the textfield, and more than one option is available in the dropdown, and you select one, then the error occurs. (e.g. marsstraat will give multiple options in the netherlands, marsstraat, almere will only give one and will work). So if you enter an address until only one option is available in the result set, then the functionality works fine.

edit: it works correctly if the streetname is unique in the dropdown list..

**Comment by ydeshayes** [comment]
Thanks ! I was able to reproduce and I push a fix ! New version 1.1.3 https://www.npmjs.com/package/material-ui-places ! I lock this conversation, feel free to open an new Issue if you have one ! @jwamsterdam
