### ISSUE TITLE
Adding types prop results in react warning

### ISSUE THREAD

**Issue by SergeyKhval** [ydeshayes/googlePlaceAutocomplete#5]
```
<GooglePlaceAutocomplete types={['geocode']} />
```

This results in the following error:
Warning: Unknown prop `types` on <input> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop

**Comment by ydeshayes** [comment]
Thank you very much for your feedback, I fixed it on the 1.1.3 version ! https://github.com/ydeshayes/googlePlaceAutocomplete/commit/2e2882e3e547fdd6be81bc7fb8a41fb03f7d06bc

**Comment by SergeyKhval** [comment]
Yeah, thanks. `npm i material-ui-places` pulls version 1.1.1

**Comment by ydeshayes** [comment]
I can't reproduce @SergeyKhval , try to pull again ?
