### ISSUE TITLE
repo not working anymore, related to material-ui update?

### ISSUE THREAD

**Issue by jwamsterdam** [ydeshayes/googlePlaceAutocomplete#6]
Hi, I have just upgraded my material-ui library to 0.17.4, but now my dropdown menu is not showing anymore for my googlePlacesAutocomplete component (tested on localhost).

Could this be related to the material-ui update? Of have changes been made by google so that it doesn't run from localhost anymore?

**Comment by ydeshayes** [comment]
Hello ! Thanks for the report.

I fixed it by setting openOnFocus prop to true by default. I test the 1.1.4 version with the 0.17.4 and 0.18.0 material-ui version. I will test the new 1.0 alpha soon.

**Comment by jwamsterdam** [comment]
Thnx, fixed it!
