### ISSUE TITLE
Moving to latest React verison ?

### ISSUE THREAD

**Issue by iroy2000** [ydeshayes/googlePlaceAutocomplete#7]
Thanks for this useful package

Currently I'm having this warning

```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
```

Do you want to bump to latest version of your dependencies ?

Thanks

**Comment by ydeshayes** [comment]
Hello, thanks for the report.

I update the React version to 15.5.4. The 1.1.5 version of the package should fix your issue.
