### ISSUE TITLE
How can I use this component with redux-form Field?

### ISSUE THREAD

**Issue by MikeKoval** [ydeshayes/googlePlaceAutocomplete#9]
I'd like to use this component inside redux-form Field, but I cannot make it working properly(
Could you please help me?

**Comment by ydeshayes** [comment]
Hello,

did you try https://github.com/erikras/redux-form-material-ui ?

**Comment by MikeKoval** [comment]
Yes, thank you. 
I've run through code of your component and created similar one using autocomplete element from redux-form-material-ui
